name: Quantum-Concept-Clarifier CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Set up Python 3.9 (or any other version you're using for your project)
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install experta  # Install Pyke for the expert system
        pip install tkinter  # Tkinter for the GUI
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install additional dependencies from requirements.txt if it exists

    # Linting with flake8
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Run tests with pytest
    - name: Test with pytest
      run: |
        pytest

    # Optional: Run any additional validation or deployment (e.g., check if the expert system works)
    - name: Validate Expert System (Optional)
      run: |
        # Add custom validation steps for your expert system if you have them, e.g.:
        # python validate_expert_system.py
        echo "Validate Expert System - add custom checks here"
